### ISSUE TITLE
Clarify macOS architecture in installer options

### ISSUE THREAD

**Issue by dennisMeeQ** [zaproxy/zaproxy-website#2043]
Hey there,

I was just trying to download the new Apple silicon version of the ZAP installer from the downloads: https://www.zaproxy.org/download/#main

The options listed for macOS are `amd64` and `aarch64`. Using a M1 mac myself I did not immediately know which option is the right one for me. So I had to google. I would have expected something like `Intel` and `Apple Silicon`.

Therefore, I would suggest to change the description of the download options to 
```
macOS (Intel - amd64) Installer
macOS (Apple Silicon - aarch64) Installer
```

What do you think?

**Comment by psiinon** [comment]
Er, I must admit I had to google that as well when I installed it on my Mac 😉

**Comment by psiinon** [comment]
Website is now updated 😁 
https://www.zaproxy.org/download/

**Comment by dennisMeeQ** [comment]
holy ... that was quick 💪
