### ISSUE TITLE
List Blogs By Author?

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy-website#219]
If there's already a way to do this please feel free to close this ticket (I couldn't find a way).

Is there a way to list blogs by author(s)? I know we allow a blog to have multiple authors but it should still be possible somehow to list articles associated with a given author.

**Comment by psiinon** [comment]
I dont know of a way, but think it would be a good addition.
We could have specific author pages where we can add as little or much (within reason) info as we like, then automatically link to all of the author's blog posts.
I'm never sure what personal link to use for myself (twitter, linkedin etc) so might use my zaproxy author page and then just link to my other social media accs from there...

**Comment by psiinon** [comment]
This wouldnt have to be just authors - I'd be happy for anyone who'd make significant ZAP contributions to have their own page...
