### ISSUE TITLE
Documentation docker run examples for current directory for all platforms

### ISSUE THREAD

**Issue by sastorsl** [zaproxy/zaproxy-website#2275]
# Docker run examples for current directory for all platforms

It would be nice to get examples for how to mount the current directory on multiple platforms, Linux, MacOS, PowerShell, Windows.

Ref `docker run ...` example on https://www.zaproxy.org/docs/docker/full-scan/ with code in https://github.com/zaproxy/zaproxy-website/blob/main/site/content/docs/docker/full-scan.md?plain=1#L55

**Comment by thc202** [comment]
IMO we should not do that, better have that in one page. But we really should not need to document all consoles out there in the first place… the user should know how their console works.

**Comment by sastorsl** [comment]
@thc202 - however, the docs _did_ state that you had to have the full path on windows. However, there _is_ a solution for this.

Anyways, created a PR. Have a look :-)
