### ISSUE TITLE
Urls for each download

### ISSUE THREAD

**Issue by rezen** [zaproxy/zaproxy-website#241]
Currently on the website downloads are tracked with a `track-event` attribute which hooks into Google Analytics. What if instead the links were to url(s) unique for each installer which redirected to the correct download? This would provide the benefit of access logs providing stats instead of just Google Analytics.

**Comment by psiinon** [comment]
We dont actually use GA to track ZAP downloads - we get those directly from github.
https://github.com/zapbot/zap-mgmt-scripts/blob/master/stats/github.py#L30
