### ISSUE TITLE
2.10 Features Blog

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy-website#263]
An issue to collect ideas for a 2.10 features blog post, similar to: https://www.zaproxy.org/blog/2020-06-04-zap-2-9-0-highlights/ only more appropriately timed 😉 

These are the things I'm currently thinking. Please edit this and add others or comment below and I'll add them.

1. Dark Mode
1. Expandable/Collapseable top panes
1. Custom Pages
1. Scriptable Encode/Decode/Hash
1. Auth polling
1. Auth Header via ENV Vars
1. Site Tree Control

**Comment by kingthorin** [comment]
I think I can tackle  the first 4 topics.

How do we want to tackle this?

- Make it a Part 1 / Part 2 thing (two posts)?
- I'll submit the first 4 then someone else can push to the same PR branch as a repo admin?

**Comment by thc202** [comment]
I think it would be better with a single post (option 2), a 3rd option is to make the blog post a "draft" so it does not get published when the PR is merged.

**Comment by kingthorin** [comment]
Okay. I'll start putting the first parts together.
