### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy-website#2708]
I haven't been doing a good job or keeping an eye on the link check job. The following have been reported as [broken by the job](https://github.com/zaproxy/zaproxy-website/actions/workflows/check-links.yml), and manually confirmed by me:

```
- code:    404
  url:     https://manosmagnus.github.io/posts/websocket-passive-scan-using-scripts-with-zap/
  parent:  file:///home/runner/work/zaproxy-website/zaproxy-website/hydra-link-checker/hof.html
  error:   Not Found
```

👆 His account seems to have been removed.

```
- code:    0
  url:     https://thetestdoctor.co.uk/
  parent:  file:///home/runner/work/zaproxy-website/zaproxy-website/hydra-link-checker/evangelists.html
  error:   <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'thetestdoctor.co.uk'. (_ssl.c:1000)>
```

👆 I've reach out to Dan via Twitter DM to find out about this.

**Comment by thc202** [comment]
It was renamed (though not sure the posts are still published).

**Comment by kingthorin** [comment]
Ya I found it, but they don't seem to work under the "new" account name either:
https://github.com/eakirtas/ManosMagnus.github.io

Also the link and twitter in his GH profile seem to be dead ends as well.

**Comment by thc202** [comment]
@eakirtas do you still have the posts published somewhere? Should we just remove the link otherwise?

**Comment by kingthorin** [comment]
For Dan Billing I'll update to: https://thetestdoctor.wordpress.com/
