### ISSUE TITLE
Dev page: How to implement a new add-on

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy-website#271]
Whether its in zap-extensions or in another repo.
Should ideally also link to templates that can be easily copied to get people started.
Could cover scan rules or are those better in another page?

**Comment by thc202** [comment]
Some done in https://www.zaproxy.org/docs/developer/creating-new-addon-in-zap-extensions/

**Comment by thc202** [comment]
Actually, closing, being tracked in #366.
