### ISSUE TITLE
Dev page: how to debug ZAP and add-ons

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy-website#272]
How to use a debugger with ZAP (which sould be relatively easy) and add-ons (which will be harder).
Ideally should be IDE independant, or if necessary include sections for different IDS. These can be added to over time of course :)

**Comment by thc202** [comment]
Done for Eclipse: https://www.zaproxy.org/docs/developer/building-zap-with-eclipse/

**Comment by thc202** [comment]
Closing, being tracked in #366.
