### ISSUE TITLE
Help/User Guide punctuation issues

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy-website#47]
There's some User Guide content that needs to be tweaked (both here and in core-help I guess). I'm happy to tackle the changes, just opening this issue so that I don't forget 👍  

One is a comma included in a link, the other is a quote included in a link, in both cases on the trailing end.

>  13525 [ZAP-SpiderThreadPool-0-thread-1] WARN org.zaproxy.zap.spider.URLCanonicalizer  - Host could not be reliably evaluated from: http://www.nottrusted.com, (on base https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules/)
> 18156 [ZAP-SpiderThreadPool-0-thread-1] WARN org.zaproxy.zap.spider.URLCanonicalizer  - Host could not be reliably evaluated from: http://www.example.com%22 (on base https://www.zaproxy.org/docs/desktop/ui/dialogs/options/dynsslcert/)

**Comment by kingthorin** [comment]
Shall I also PR fixes here for the two items? Or just let it get fixed in the next update cycle? Or is that content being auto-PRd by an action?

**Comment by thc202** [comment]
Yes, better to fix now here (e.g.the core help will take a while to be released).
