### ISSUE TITLE
Migrate/Create Supporters Page/Section

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy-website#5]
@kingthorin wrote:

> https://raw.githubusercontent.com/OWASP/www-project-zap/7a98aa641f7f67b593095e3aae5dbfc6ce3080d9/tab_supporters.md should be migrated or other wise added here. (I have no idea how up-to-date that content is, it was based on the OWASP wiki.)

**Comment by kingthorin** [comment]
Should we continue/start with this list, is it still accurate? (Please just edit this comment to add/remove as you see fit.)

* [Mozilla](https://www.mozilla.org)
* [The Linux Foundation](https://www.linuxfoundation.org/)
* [Segment](https://segment.com/)
* [OWASP](https://www.owasp.org)
* [Sage](https://www.sage.co.uk)
* [Google](https://www.google.com)
* [Microsoft](https://www.microsoft.com)
* [Hacktics, Ernst & Young](https://www.hacktics.com/)
* [DinoSec](https://www.dinosec.com/)
* [Denim Group](https://www.denimgroup.com)
* [Aspect Security](http://www.aspectsecurity.com/)
* [SecureIdeas](http://secureideas.net)
* [UtiliSec](http://utilisec.com)
* [encription](http://www.encription.co.uk/)
* [Accenture Digital](https://www.accenture.com/us-en/digital-index.aspx)
