### ISSUE TITLE
Gradle build fails for zap-extensions due to out of memory errors

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [zaproxy/zaproxy-website#646]
`./gradlew build` fails causing nullpointer exceptions and many others but builds succesfully with `./gradlew -Dorg.gradle.jvmargs=-Xmx2g`.
The documentation should be updated for building ALL the extensions in zap-extensions.

**Comment by thc202** [comment]
Sounds good to me but we should be really clear that you don't need to build all add-ons to build/work on specific add-ons (in fact you should rarely need to build all add-ons at once).

**Comment by ArkaprabhaChakraborty** [comment]
I think that is already specified in the docs. It's just a change in one section of the doc.

**Comment by ArkaprabhaChakraborty** [comment]
I just realised ... I might have created this issue in wrong repo :)

**Comment by thc202** [comment]
This repo is fine, the dev documentation is being moved to the website.

**Comment by thc202** [comment]
I thought you were referring to the instructions in https://www.zaproxy.org/docs/developer/quick-start-build/ not the zap-extensions repo. Better change that to point to the main website dev page.

**Comment by thc202** [comment]
Right.

**Comment by ArkaprabhaChakraborty** [comment]
Okay, but where do I add the new gradle command to build the extension in the website? I didn't find any build area specifically made for zap-extension contributors.

**Comment by kingthorin** [comment]
I'd suggest https://www.zaproxy.org/docs/developer/quick-start-build/ just before the "Running ZAP from Source" heading. The bits before that are about building/copying individual add-ons. So a small subsection with a build all add-ons bit would fir I think.

**Comment by thc202** [comment]
Might be good to link to official documentation, e.g. one could add that arg to the user's `gradle.properties` file rather on each command that involves all add-ons. https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

(All add-ons are built when calling `copyZapAddOn`.)
