### ISSUE TITLE
Docker File is having references to files which are not present in Repo causing failure

### ISSUE THREAD

**Issue by preetkaran20** [zaproxy/zaproxy-website#99]
**- Do you want to request a *feature* or report a *bug*?**
I think it is a bug.
**- What is the current behavior?**
Currently running docker file fails because of Copy command pointing to files which are not present in the Repository like Renovate and yarn.lock
Alse in ./bin/build file there is a mention to variable called realpath but i am not sure if it is expected to be created. If there is a mention then please ignore, if not then i think we need to handle that.
**- If the current behavior is a bug, please provide the steps to reproduce.**
We can remove them so that command work perfectly
**- What is the expected behavior?**
Docker file should run properly.
**- Please mention your node.js, NPM, Hugo and operating system version.**
Mac OS, I think it is not related to node version

**Comment by thc202** [comment]
Feel free to raise a PR removing them.

**Comment by thc202** [comment]
Re the `realpath`, that's a command.

**Comment by preetkaran20** [comment]
I will raise a PR.

**Comment by preetkaran20** [comment]
@thc202 realpath , is this a Linux command ?

**Comment by preetkaran20** [comment]
https://github.com/zaproxy/zaproxy-website/pull/100

**Comment by preetkaran20** [comment]
@thc202 please review https://github.com/zaproxy/zaproxy-website/pull/98, this is related to docker command not working if present working directory is having space

**Comment by preetkaran20** [comment]
> Re the `realpath`, that's a command.
In Mac it is not there so this command will fail in Mac os. can we use some kind of alternative to it or may be worth mentioning solution for Mac in readme ?

**Comment by thc202** [comment]
Yeah, if there's an alternative that works in more OSes.

**Comment by thc202** [comment]
Closing, done in #100.
